/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import AgregaProducto.AgregaProducto;
import DTO.ProductoDTO;
import javax.swing.ImageIcon;

/**
 *
 * @author labcisco
 */
public class MenuPrincipal extends javax.swing.JFrame {

    AgregaProducto agregarProductos;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {

        agregarProductos = new AgregaProducto();
        initComponents();
        inicializarProductos();
    }

    private void inicializarProductos() {
        
         ProductoDTO amlo = new ProductoDTO(007001, "amlo", "loret", "revista", "segunda", 200, "peridismo", 10);

        agregarProductos.agregarProducto(amlo);
        ProductoDTO libroRapunzel = new ProductoDTO(1234, "Rapunzel", "Joaquin", "libro", "Primera", 300, "aventura", 10);

        agregarProductos.agregarProducto(libroRapunzel);

        ProductoDTO libroRapunzel2 = new ProductoDTO(1235, "Rapunzel", "disney", "libro", "segunda", 4500, "aventura", 20);
        agregarProductos.agregarProducto(libroRapunzel2);

        ProductoDTO libroHarryPotter = new ProductoDTO(97805, "Harry Potter and the Sorcerer's Stone", "J.K. Rowling", "Libro", "Scholastic Inc.", 6.99, "Aventura", 20);
        agregarProductos.agregarProducto(libroHarryPotter);

        ProductoDTO libroDracula = new ProductoDTO(97800, "Dracula", "Bram Stoker", "Libro", "Dover Publications", 5.99, "Terror", 20);
        agregarProductos.agregarProducto(libroDracula);

        ProductoDTO libroCienAñosSoledad = new ProductoDTO(48641, "Cien años de soledad", "Gabriel García Márquez", "Libro", "Harper & Row", 8.99, "Ficción", 30);
        agregarProductos.agregarProducto(libroCienAñosSoledad);

        ProductoDTO libroElPrincipito1 = new ProductoDTO(1, "El Principito", "Antoine de Saint-Exupéry", "Libro", "Editorial", 10.99, "Aventura", 50);
        agregarProductos.agregarProducto(libroElPrincipito1);

        ProductoDTO libroElPrincipito2 = new ProductoDTO(2, "El Principito", "Otro Autor", "Libro", "Otra Editorial", 8.99, "Fantasía", 30);
        agregarProductos.agregarProducto(libroElPrincipito2);

        // Tercer libro de El Principito
        ProductoDTO libroElPrincipito3 = new ProductoDTO(3, "El Principito", "Otro Autor Más", "Libro", "Otra Editorial Más", 12.99, "Aventura", 40);
        agregarProductos.agregarProducto(libroElPrincipito3);

        ProductoDTO tiktoks = new ProductoDTO(312345, "como ser tiktoker", "jorgendo43", "libro", "primera", 12.99, "importante", 40);
        agregarProductos.agregarProducto(tiktoks);
        
           ProductoDTO llorona = new ProductoDTO(31234589, "la llorona", "jorgendo43", "libro", "segunda", 15.99, "importante", 50);
        agregarProductos.agregarProducto(llorona);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTodosLosLibros = new javax.swing.JButton();
        bnBusquedaNombre = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        btnCategoria = new javax.swing.JButton();
        btnAutor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.activeCaptionBorder);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lybrari.jpg"))); // NOI18N

        btnTodosLosLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mejoresValorados.jpg"))); // NOI18N
        btnTodosLosLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosLosLibrosActionPerformed(evt);
            }
        });

        bnBusquedaNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pornombre.jpg"))); // NOI18N
        bnBusquedaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnBusquedaNombreActionPerformed(evt);
            }
        });

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButton1.setText("Usuario");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("TODOS LOS LIBROS");

        btnCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fgfghghf.jpg"))); // NOI18N
        btnCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaActionPerformed(evt);
            }
        });

        btnAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gdfgfd.jpg"))); // NOI18N
        btnAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("LIBROS POR AUTOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(bnBusquedaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAutor)
                                        .addGap(44, 44, 44))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(btnTodosLosLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btnCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(80, 80, 80)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jToggleButton1)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTodosLosLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bnBusquedaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnBusquedaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnBusquedaNombreActionPerformed
        BusquedaPorNombre bu = new BusquedaPorNombre();
        bu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bnBusquedaNombreActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        MenuUsuario MU = new MenuUsuario();
        MU.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btnTodosLosLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosLosLibrosActionPerformed
frmTodosLosLibros todosLoLibros= new frmTodosLosLibros();
todosLoLibros.setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnTodosLosLibrosActionPerformed

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed
frmProductosPorCategoria categorias = new frmProductosPorCategoria();
categorias.setVisible(true);
this.dispose();

    }//GEN-LAST:event_btnCategoriaActionPerformed

    private void btnAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorActionPerformed
frmProductosPorAutor autor = new frmProductosPorAutor();
autor.setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnAutorActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnBusquedaNombre;
    private javax.swing.JButton btnAutor;
    private javax.swing.JButton btnCategoria;
    private javax.swing.JButton btnTodosLosLibros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
